export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RESPONSE_SUCCESS = "Success";
export const RESPONSE_ERROR = "Error";

export const SET_FACT_LIST_SUCCESS = "SET_FACT_LIST_SUCCESS";
export const SET_FACT_LIST_FAIL = "SET_FACT_LIST_FAIL";
export const MOVE_TO_DETAILED_LIST = "MOVE_TO_DETAILED_LIST";
export const MOVE_TO_FACT_LIST = "MOVE_TO_FACT_LIST";